INSERT INTO SUCCESS_STORIES VALUES (1, 'Fever') ON CONFLICT DO NOTHING;
INSERT INTO SUCCESS_STORIES VALUES (2, 'Sugar') ON CONFLICT DO NOTHING;
INSERT INTO SUCCESS_STORIES VALUES (3, 'Skin Problem') ON CONFLICT DO NOTHING;

INSERT INTO PERSON VALUES (1, 'Selva','Madurai') ON CONFLICT DO NOTHING;
INSERT INTO PERSON VALUES (2, 'Vineeth','Theni') ON CONFLICT DO NOTHING;
INSERT INTO PERSON VALUES (3, 'Nagarajan','Covai') ON CONFLICT DO NOTHING;

INSERT INTO AVAILABLE_FORMAT VALUES (1, 'document','Yes') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (2, 'pdf','No') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (3, 'video','Yes') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (4, 'audio','Yes') ON CONFLICT DO NOTHING;

INSERT INTO AVAILABLE_FORMAT VALUES (5, 'document','Yes') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (6, 'pdf','No') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (7, 'video','Yes') ON CONFLICT DO NOTHING;
INSERT INTO AVAILABLE_FORMAT VALUES (8, 'audio','Yes') ON CONFLICT DO NOTHING;

INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (1, 1) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (1, 2) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (1, 3) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (1, 4) ON CONFLICT DO NOTHING;

INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (2, 5) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (2, 6) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (2, 7) ON CONFLICT DO NOTHING;
INSERT INTO PERSON_AVAILABLE_FORMAT VALUES (2, 8) ON CONFLICT DO NOTHING;

